# Generated by Django 3.2 on 2022-07-23 12:39

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('intro', models.TextField(blank=True, null=True)),
                ('microsoft_access_token', models.CharField(max_length=150)),
                ('interest_out', models.CharField(max_length=100)),
                ('interest_in', models.CharField(max_length=100)),
                ('interest_leisure', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('gender_prefer', models.CharField(max_length=50)),
                ('personality', models.CharField(max_length=50)),
                ('language_sp1', models.CharField(max_length=50)),
                ('language_sp2', models.CharField(max_length=50)),
                ('priority1', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50)),
                ('priority2', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50)),
                ('priority3', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50)),
                ('user_status', models.BooleanField(default=False)),
            ],
        ),
    ]
