# Generated by Django 3.2 on 2022-07-24 09:20

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User(first_name="Dylis", last_name="Huang", contact_email="345@gmail.com", intro="hi!", microsoft_access_token="00002", interest_out="sport", interest_in="singing", interest_leisure="coffee", purpose="make friends", gender="female", gender_prefer="female", personality="extravert", language_sp1="Germany", language_sp2="French", priority1="1", priority2="2", priority3="3").save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220724_0910'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
