# Generated by Django 3.2 on 2022-07-25 19:21

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User(first_name="Ben", last_name="Ace", contact_email="321@gmail.com", intro="haha", microsoft_access_token="00002", interest_out="nature", interest_in="reading", interest_leisure="video", purpose="make friends", gender="male", gender_prefer="female", personality="extravert", language_sp1="English", language_sp2="Irish", priority1="1", priority2="2", priority3="3").save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220725_1803'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
