# Generated by Django 3.2 on 2022-07-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220725_1938'),
    ]

    operations = [
    ]
