# Generated by Django 3.2 on 2022-08-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220727_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeAccountId', models.CharField(max_length=150)),
                ('username', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
