# Generated by Django 3.2 on 2022-08-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_useraccount_accesstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='accessToken',
        ),
    ]
