# Generated by Django 3.2 on 2022-07-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypreference', '0002_auto_20220727_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypreference',
            old_name='priority2_purposes',
            new_name='priority2_purpose',
        ),
    ]
