# Generated by Django 3.2 on 2022-07-28 10:41

from django.db import migrations

from mypreference.models import MyPreference


def create_data(apps, schema_editor):
    MyPreference = apps.get_model('mypreference', 'MyPreference')
    MyPreference(interest_out="sport", interest_in="reading", interest_leisure="video", purpose="make friends", gender="female",
                 personality="extravert", language="Spanish", priority1_interests="1", priority2_purpose="2", priority3_trait="3", gender_prefer="female").save()


class Migration(migrations.Migration):

    dependencies = [
        ('mypreference', '0003_rename_priority2_purposes_mypreference_priority2_purpose'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
