# Generated by Django 3.2 on 2022-08-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypreference', '0004_auto_20220728_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypreference',
            old_name='priority1_interests',
            new_name='priority1_interests_out',
        ),
        migrations.RenameField(
            model_name='mypreference',
            old_name='priority2_purpose',
            new_name='priority2_interests_in',
        ),
        migrations.RenameField(
            model_name='mypreference',
            old_name='priority3_trait',
            new_name='priority3_interests_lei',
        ),
        migrations.AddField(
            model_name='mypreference',
            name='priority4_purpose',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypreference',
            name='priority5_trait',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
