# Generated by Django 3.2 on 2022-08-06 11:52

from django.db import migrations

def create_data(apps, schema_editor):
    MyPreference = apps.get_model('mypreference', 'MyPreference')
    MyPreference(interest_out="sport", interest_in="singing", interest_leisure="reading", purpose="make friends", gender="female",
                 personality="extravert", language="Japanese", priority1_interests_out="2", priority2_interests_in="2", priority3_interests_lei="3", priority4_purpose ="1", priority5_trait="2" ,gender_prefer="female").save()

class Migration(migrations.Migration):

    dependencies = [
        ('mypreference', '0005_auto_20220804_1707'),
    ]

    operations = [
         migrations.RunPython(create_data),
    ]
