# Generated by Django 3.2 on 2022-08-06 12:26

from django.db import migrations

def update_data(apps, schema_editor):
    MyPreference = apps.get_model('mypreference', 'MyPreference')
    m = MyPreference.objects.get(id=2)
    m.interest_in = "Yoga"
    m.interest_leisure = "Reading"
    m.purpose = "Make friends"
    m.gender = "Female"
    m.personality = "Ambivert"
    m.gender_prefer = "Female"
    m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mypreference', '0007_auto_20220806_1221'),
    ]

    operations = [
        migrations.RunPython(update_data),
    ]
