# Generated by Django 3.2 on 2022-08-07 09:04

from django.db import migrations

def create_data(apps, schema_editor):
    MyPreference = apps.get_model('mypreference', 'MyPreference')
    MyPreference(interest_out="Aqua", interest_in="Exercising", interest_leisure="Coffee shop", purpose="Make friends", gender="Male",
                 personality="Ambivert", language="Mandarin", priority1_interests_out="3", priority2_interests_in="2", priority3_interests_lei="3", priority4_purpose="2", priority5_trait="1", gender_prefer="Any").save()

class Migration(migrations.Migration):

    dependencies = [
        ('mypreference', '0010_auto_20220807_0859'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
