# Generated by Django 3.2 on 2022-08-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypreference', '0012_mypreference_homeaccountid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypreference',
            name='homeAccountId',
        ),
    ]
