# Generated by Django 3.2 on 2022-08-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypreference', '0013_remove_mypreference_homeaccountid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypreference',
            name='gender_prefer',
        ),
    ]
