# Generated by Django 3.2 on 2022-08-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        
    ]
