# Generated by Django 3.2 on 2022-08-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20220814_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='date',
        ),
    ]
