# Generated by Django 3.2 on 2022-08-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_chats_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='date',
            field=models.CharField(default=20220815, max_length=50),
            preserve_default=False,
        ),
    ]
